name: 'github-helpers'
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]
permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  auto-assignments-for-pr:
    name: auto-assignments-for-pr
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
